# Generated by Django 4.2.1 on 2023-05-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='freedom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pic')),
                ('tit', models.CharField(max_length=250)),
                ('des', models.TextField()),
            ],
        ),
    ]
