# Generated by Django 4.2.1 on 2023-05-31 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1app', '0002_freedom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='freedom',
        ),
    ]
